Repository googleapis/google-auth-library-ruby, pull requests merged in 2018-07, with the labels that each got.

#141 Update README.md
  README.md
Labels: cla: yes, type: cleanup

#107 Avoids redundant class method definition
  lib/googleauth/json_key_reader.rb
  lib/googleauth/service_account.rb
Labels: cla: yes, priority: p2, type: cleanup

#139 Update os gem dependency
  googleauth.gemspec
Labels: cla: yes, type: cleanup

#145 Warn when using cloud sdk credentials
  .rubocop.yml
  lib/googleauth/client_id.rb
  lib/googleauth/credentials.rb
  lib/googleauth/credentials_loader.rb
  lib/googleauth/default_credentials.rb
  spec/googleauth/client_id_spec.rb
  spec/googleauth/credentials_spec.rb
  spec/googleauth/get_application_default_spec.rb
  spec/googleauth/user_refresh_spec.rb
Labels: cla: yes
