Repository googleapis/google-auth-library-ruby, pull requests merged in 2019-05, with the labels that each got.

#211 Credentials Environment Variable Refactor
  lib/googleauth/credentials.rb
  spec/googleauth/credentials_spec.rb
Labels: cla: yes, type: feature request

#214 Fix Rubocop errors
  Gemfile
  lib/googleauth/user_refresh.rb
Labels: cla: yes, type: cleanup

#212 Credentials: Use methods instead of constants
  .rubocop.yml
  lib/googleauth/credentials.rb
  spec/googleauth/credentials_spec.rb
Labels: cla: yes

#215 Fix the gcloud command to avoid spamming stderr when unauthorized.
  lib/googleauth/credentials_loader.rb
Labels: cla: yes
